### ISSUE TITLE
Build errors stop build in 10.10

### ISSUE THREAD

**Issue by djbclark** [sveinbjornt/osxiconutils#2]
7 warnings, 5 errors under 10.10 Yosemite / XCode 6.3.2

Update to recommended settings pic2icns Group

IconFamily.m:1210:128: Incomplete format specifier

IconFamily/IconFamily.m:1255:9: Use of undeclared identifier 'CGDirectPaletteRef'

IconFamily/IconFamily.m:1264:9: Use of undeclared identifier 'cgPal'

IconFamily/IconFamily.m:1264:17: Implicit declaration of function 'CGPaletteCreateDefaultColorPalette' is invalid in C99

IconFamily/IconFamily.m:1276:32: Implicit declaration of function 'CGPaletteGetIndexForColor' is invalid in C99

IconFamily/IconFamily.m:1276:58: Use of undeclared identifier 'cgPal'

IconFamily/IconFamily.m:1289:58: Use of undeclared identifier 'cgPal'

IconFamily/IconFamily.m:1296:9: Implicit declaration of function 'CGPaletteRelease' is invalid in C99

IconFamily/IconFamily.m:1296:26: Use of undeclared identifier 'cgPal'

IconFamily/IconFamily.m:1300:127: Incomplete format specifier

IconFamily.m:1376:127: Incomplete format specifier
